src/CS585Grader/SubmissionBundle/Entity/Grade.php
<?php
/**
 * This file is part of CS585Grader.
 *
 * Copyright (c) 2014 Tyler Romeo
 *
 * CS585Grader is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * CS585Grader is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with CS585Grader.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @file
 * @author Tyler Romeo <tylerromeo@gmail.com>
 * @copyright 2013 Tyler Romeo
 * @license https://www.gnu.org/licenses/agpl-3.0.html GNU Affero General Publi\
c License
 */

namespace CS585Grader\SubmissionBundle\Entity;

use CS585Grader\AccountBundle\Entity\User;
use Symfony\Component\HttpFoundation\File\Exception\FileNotFoundException;
use Symfony\Component\HttpFoundation\File\File;

/**
 * Represents a student's grade on a given assignment
 *
 * @package CS585Grader\SubmissionBundle\Entity
 */
class Grade {
	/** @var Assignment The assignment this grade is for */
	protected $assignment;

	/** @var \CS585Grader\AccountBundle\Entity\User Student who has the grade */
	protected $user;

	/** @var int|null The actual grade */
	protected $grade;

	/** @var string|null File key/name */
	protected $fileKey;

	/** @var File */
	protected $file;

	/** @var string|null Reason for the grade (message key) */
	protected $reason;

	/** @var string|null Extended reason */
	protected $extendedReason;

	/**
	 * Make a new grade
	 *
	 * @param Assignment $assignment Assignment the grade is for
	 * @param User $user User to assign to
	 * @param int|null $grade Grade, or null for ungraded
	 * @param string|null $reason Reason for the grade (message key)
	 */
	public function __construct( Assignment $assignment, User $user, $grade, $reason = null ) {
		$this->assignment = $assignment;
		$this->user = $user;
		$this->grade = $grade;
		$this->reason = $reason;
	}

	/**
	 * Get the user the grade belongs to
	 *
	 * @return User
	 */
	public function getUser() {
		return $this->user;
	}

	/**
	 * Get the assignment this grade is on
	 *
	 * @return Assignment
	 */
	public function getAssignment() {
		return $this->assignment;
	}

	/**
	 * Get the grade
	 *
	 * @return int|null
	 */
	public function getGrade() {
		return $this->grade;
	}

	/**
	 * Set the grade for the assignment
	 *
	 * @param int|null $grade
	 */
	public function setGrade( $grade ) {
		$this->grade = $grade;
	}

	/**
	 * Get the brief grade reasons
	 *
	 * @return null|string
	 */
	public function getGradeReason() {
		return $this->reason;
	}

	/**
	 * Set the short reason for the grade
	 *
	 * @param string $reason
	 */
	public function setGradeReason( $reason ) {
		$this->reason = $reason;
	}

	/**
	 * Get the extended reason for the grade
	 *
	 * @return null|string
	 */
	public function getGradeExtendedReason() {
		if ( is_resource( $this->extendedReason ) ) {
			return stream_get_contents( $this->extendedReason );
		} else {
			return $this->extendedReason;
		}
	}

	/**
	 * Set the extended reason for the grade
	 *
	 * @param string|null $reason
	 */
	public function setGradeExtendedReason( $reason ) {
		$this->extendedReason = $reason;
	}

	/**
	 * Get the file for the assignment
	 *
	 * @return File|null
	 */
	public function getFile() {
		if ( !is_object( $this->file ) ) {
			try {
				$this->file = new File( $this->fileKey );
			} catch ( FileNotFoundException $e ) {
				$this->file = false;
			}
		}

		return $this->file ?: null;
	}

	/**
	 * Set the uploaded file
	 *
	 * @param File|null $file
	 */
	public function setFile( File $file = null ) {
		$this->file = $file;
		$this->fileKey = $file ? $file->getPathname() : null;
	}
}

src/CS585Grader/SubmissionBundle/Controller/DefaultController.php
<?php
/**
 * This file is part of CS585Grader.
 *
 * Copyright (c) 2014 Tyler Romeo
 *
 * CS585Grader is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * CS585Grader is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with CS585Grader.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @file
 * @author Tyler Romeo <tylerromeo@gmail.com>
 * @copyright 2013 Tyler Romeo
 * @license https://www.gnu.org/licenses/agpl-3.0.html GNU Affero General Public License
 */

namespace CS585Grader\SubmissionBundle\Controller;

use CS585Grader\SubmissionBundle\Entity\Assignment;
use CS585Grader\SubmissionBundle\Entity\Grade;
use Doctrine\ORM\Query\Expr;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

/**
 * Main controller that provides logic for submitting assignments
 *
 * @package CS585Grader\SubmissionBundle\Controller
 */
class DefaultController extends Controller
{
	/**
	 * Get the home page
	 *
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
	public function indexAction() {
		/** @var \Doctrine\ORM\EntityManager $em */
		$em = $this->getDoctrine()->getManager();
		$res = $em->createQueryBuilder()
			->select( 'a', 'g' )
			->from( 'CS585GraderSubmissionBundle:Assignment', 'a' )
			->leftJoin( 'a.submissions', 'g', Expr\Join::WITH, 'g.user = :user' )
			->orderBy( 'a.dueDate' )
			->setParameter( 'user', $this->getUser() )

			->getQuery()
			->getResult();

		return $this->render(
			'CS585GraderSubmissionBundle:Default:index.html.twig',
			[ 'assignments' => $res ]
		);
	}

	/**
	 * Action for users to manually submit their assignments
	 *
	 * @param Request $request
	 * @param Assignment $assignment
	 *
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
	public function submitAction( Request $request, Assignment $assignment ) {
		$grade = new Grade( $assignment, $this->getUser(), 'Submitted' );
		$form = $this->createFormBuilder( $grade )
			->add( 'file', 'cs587_submission', [ 'assignment' => $assignment, 'user' => $this->getUser() ] )
			->add( 'submit', 'submit' )
			->getForm();

		$form->handleRequest( $request );
		if ( $form->isValid() ) {
			$grade->setFile( $form->get( 'file' )->getData() );
			$em = $this->getDoctrine()->getManager();
			$em->persist( $grade );
			$em->flush();

			return $this->redirect( $this->generateUrl( 'cs585_grader_submission_homepage' ) );
		}

		return $this->render(
			'CS585GraderSubmissionBundle:Default:submit.html.twig',
			[ 'form' => $form->createView() ]
		);
	}
}

src/CS585Grader/SubmissionBundle/Resources/views/Default/index.html.twig
{% extends '::layout.html.twig' %}

{% block title %}Home{% endblock %}

{% block nav_page_home %}active{% endblock %}

{% block javascripts %}
	{% javascripts '@moment_js'
	'@CS585GraderSubmissionBundle/Resources/public/js/countdown.js' %}
	<script src="{{ asset_url }}"></script>
	{% endjavascripts %}
{% endblock %}

{% block content %}
	<div class="panel panel-default">
		<div class="panel-heading">Assignments</div>
		<div class="panel-body">
			<strong>Reminder:</strong> Assignments will be automatically collected
			from the repository selected in your profile. You <em>must</em> make a
			tag with the same name as the assignment.
		</div>

		<table class="table">
			<thead>
			<tr>
				<th>#</th>
				<th>Name</th>
				<th>Due Date</th>
				<th>Time Remaining</th>
				<th>Grade</th>
				<th>Grade Reason</th>
				{% if not is_granted( 'ROLE_OAUTH_USER' ) %}
					<th>Manual Submit</th>
				{% endif %}
			</tr>
			</thead>
			<tbody>
			{% for assignment in assignments %}
				<tr>
					<td>{{ loop.index }}</td>
					<td>{{ assignment.name }}</td>
					<td>{{ assignment.dueDate|date('Y-m-d H:i:s') }}</td>
					<td class="cs585-countdown" data-duedate="{{ assignment.dueDate|date('c') }}"></td>
					<td>
						{% if assignment.submissions|length > 0 and assignment.submissions[0].grade is not null %}
							<div class="dropdown">
								<button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
									{{ assignment.submissions[0].grade }}
									<span class="caret"></span>
								</button>
								<ul class="dropdown-menu">
									<li>{{ assignment.submissions[0].gradeExtendedReason|nl2br }}</li>
								</ul>
							</div>
						{% else %}
							{{ 'Not Graded'|trans }}
						{% endif %}
					</td>
					<td>
						{% if assignment.submissions|length > 0 %}
							{{ assignment.submissions[0].gradeReason|trans }}
						{% endif %}
					</td>
					<td>
						{% if not is_granted( 'ROLE_OAUTH_USER' ) and assignment.submissions|length == 0 %}
							<a class="btn btn-primary"
							   href="{{ path('cs585_grader_submission_submit', { 'name': assignment.name }) }}">
								Manual Submit
							</a>
						{% endif %}
					</td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
	</div>
{% endblock %}

src/CS585Grader/SubmissionBundle/Resources/views/Default/submit.html.twig
{% extends '::layout.html.twig' %}

{% block title %}Submit{% endblock %}

{% block nav_page_home %}active{% endblock %}

{% block content %}
	{{ form( form ) }}
{% endblock %}